### ISSUE TITLE
bump to api v2.0.4?

### ISSUE THREAD

**Issue by blathers123** [ms32035/firefly-iii-client#17]
Hello,

Would it be possible to update this library to match the latest v2 of the API?

**Comment by ms32035** [comment]
Will get to it over the weekend

**Comment by ms32035** [comment]
@blathers123 I gave it a try, but there's an issue with the spec:

```
Errors:
        -attribute components.schemas.RecurrenceTransactionUpdate.required is not of type `array`
Warnings:
        -attribute components.schemas.RecurrenceTransactionUpdate.required is not of type `array`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

This happens quite often. Best you refer to @jc5

**Comment by JC5** [comment]
Mmm, what am I looking at, exactly? The `RecurrenceTransactionUpdate` does not have field `required`.

**Comment by ms32035** [comment]
@JC5 it's not a field, it's an attribute
https://api-docs.firefly-iii.org/firefly-iii-2.0.4-v1.yaml line 17019
Something like this is missing
```
    RecurrenceTransactionStore:
      type: object
      required:
        - description
        - amount
        - source_id
        - destination_id
```
Maybe an empty array is needed where no fields are required

**Comment by JC5** [comment]
Ah nice. I've changed it and I'll push an update in a minute :+1:

**Comment by ms32035** [comment]
Thanks @JC5 
Two more new now:
```
Errors:
        -attribute components.schemas.BudgetLimitV2Array.BudgetLimitV2Read is not of type `schema`
        -attribute paths.'/v2/preferences/{name}'(get).responses.200.content.'application/vnd.api+json'.schema.#/components/schemas/PreferenceSingle is missing
```

The first one is a typo, because it should be `BudgetLimitReadV2`
The second one references a completely missing schema `PreferenceSingle`

Apologies for this painful back and forth, but I'd guess there will be a few more iterations.

**Comment by JC5** [comment]
Not a problem at all, sometimes it's the only way to pick these things up.  I'll get back to you!

**Comment by JC5** [comment]
Done!

**Comment by ms32035** [comment]
Thank @JC5, looks like the webserver hasn't refreshed

**Comment by ms32035** [comment]
@JC5 the v2 spec is actually broken. only 1.9k lines vs 20k in v1

**Comment by JC5** [comment]
There aren't that many v2 endpoints yet 🙈

**Comment by ms32035** [comment]
🤦‍♂️ got confused with the versions and dates. The v2 file is still showing `2023-07-30T09:56:04+00:00` as generation timestamp

**Comment by JC5** [comment]
Mmmm that will be the cdn. I'll see if I can purge it.

**Comment by JC5** [comment]
The CDN is purged, 2.0.5 is also online. No changes in v1, but the chart endpoints have been extended (and made consistent). There are now two charts available in v2.

**Comment by ms32035** [comment]
@JC5 v1 still fails with the same same error. Not sure what the issue is, but there seems to be some inconsistency between schema and properties for what's required here:
```
    RecurrenceTransactionUpdate:
      type: object
      required: []
      properties:
        id:
          type: string
          format: string
          required: true
          example: "ID of the recurring transaction. Not to be confused with the ID of the recurrence itself. Is marked as REQUIRED but can be skipped when there is only ONE transaction."
```

v2 generates fine now

**Comment by JC5** [comment]
Feel free to suggest a solution, I'm out of ideas.

**Comment by ms32035** [comment]
@JC5 this generates correctly
```
    RecurrenceTransactionUpdate:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: string
          example: "ID of the recurring transaction. Not to be confused with the ID of the recurrence itself. Is marked as REQUIRED but can be skipped when there is only ONE transaction."
```

**Comment by JC5** [comment]
Nice, fixed.

**Comment by ms32035** [comment]
Release 2.0.5.0 is out.
Thanks @JC5
